<a href="https://colab.research.google.com/github/mwangimarie43-art/Python_1/blob/main/karibu.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
a=8
print(a)
2+3

8

5

In [21]:
name="Mary"
print(name)
print(name.lower())
print(name.upper())
age=21
is_student=True
weight=49
print(type(name))
print(type(age))
print(type(is_student))
print(type(weight))

def greet(name):
  print("Hi",name)
greet("Karimi")

Mary
mary
MARY
<class 'str'>
<class 'int'>
<class 'bool'>
<class 'int'>
Hi Karimi

In [18]:
nums=[1,2,3,4,5,6]
print(type(nums))
for num in nums:
  if num <= 5:
    print(num)
  else:
   print("max")

print(nums)
print(nums[2])
nums.append(12)
print(nums)
nums.pop()
print(nums)
if num in nums:
  if num%2 ==0 :
    print(num)
  else:
    print("odd")

<class 'list'>
1
2
3
4
5
max
[1, 2, 3, 4, 5, 6]
3
[1, 2, 3, 4, 5, 6, 12]
[1, 2, 3, 4, 5, 6]
6

In [23]:
def student(name,age):
  if age < 18:
    print("student is underage")
  else:
    return age

  print("My name is ", name, "Am" ,age, "years old")

student("Imani",20)

20

In [27]:
import pandas as pd
data={
    "review":["book","excellent","useful"],
    "rating":[3,4,5]
}
df = pd.DataFrame(data)

df.head()

      review  rating
0       book       3
1  excellent       4
2     useful       5

In [30]:
import pandas as pd

amazon_df = pd.read_csv('/content/AmazonReviews.csv')
display(amazon_df.head(10))

,id,profileName,text,date,title,rating,images,helpful,variant:
0,R2IOYW8GNJDUAZ,G. W.,"So far I've only made it to ""for loops"" chapte...","Reviewed in the United States on December 26, ...","Recommend getting, but also get proof of Pytho...",5.0 out of 5 stars,NaN,19,NaN
1,R3NY3KXV8N46K7,Owen C. Marshall,"With the lockdown from the global pandemic, I ...","Reviewed in the United States on May 7, 2020","Easy to Follow, Good Intro for Self Learner",5.0 out of 5 stars,NaN,13,NaN
2,R270DXU8YVGFPX,Umar,"In embarking on my journey to learn Python, I ...","Reviewed in the United States on December 15, ...",Great for starting your journey on learning py...,5.0 out of 5 stars,NaN,0,NaN
3,R13Z1BSD70DMKJ,Dan,Have had this for one day and the cover is alr...,"Reviewed in the United States on July 5, 2019",Great inner content! Not that great outer qual...,4.0 out of 5 stars,NaN,341,NaN
4,R37T2H59DR3WSL,Zerono,"Wanted to add in a few tips, so beginners don'...","Reviewed in the United States on February 16, ...",Tips for beginners,5.0 out of 5 stars,NaN,10,NaN
5,R3G7MCXLOZGDTO,Some Guy,This is probably one of the best introductory ...,"Reviewed in the United States on January 1, 2021",Great,5.0 out of 5 stars,NaN,3,NaN
6,R2M2AT6AHNOA5V,geekandglitter,I am a beginner/intermediate Python programmer...,"Reviewed in the United States on December 3, 2020",Can be used both as a reference and a teaching...,5.0 out of 5 stars,NaN,5,NaN
7,R1HV0O7Q9M36FN,WF,"First, I just want to say thank you for allowi...","Reviewed in the United States on August 20, 2020",I have a whole bookshelf on Python books. Hand...,5.0 out of 5 stars,NaN,4,NaN
8,R19B86UCRHN8C4,Willger Torres,Está diseñado en un proceso formativo simple. ...,"Reviewed in the United States on June 9, 2025",simple y con el detalle de aprendizaje adecuado,5.0 out of 5 stars,NaN,0,NaN
9,R32IHODPYQN8CD,N8,I've had some programming experience in the pa...,"Reviewed in the United States on March 28, 2021",Very detailed and clearly explained,5.0 out of 5 stars,NaN,6,NaN